/*
 * (ZoneRegistrationKeyProvider.cs)
 *------------------------------------------------------------
 * Created - 7/1/2026
 * Created by - Seliris
 *-------------------------------------------------------------
 */

using SystemTools.Logger;
using SystemTools.Storage;

namespace SystemTools.Security;

/// <summary>
/// Provides the Ed25519 keypair that gates zone-process registration with
/// ZoneManager. ZoneManager holds the public key and verifies; each zone
/// process holds the private seed and signs. The seed never crosses the
/// wire — a zone proves possession by signing a timestamp, mirroring the
/// client key-auth scheme.
/// </summary>
/// <remarks>
/// This is the zone-registration analog of <see cref="SessionKeyProvider"/>,
/// but it deliberately does <b>not</b> share that class's single
/// <c>LoadOrCreate</c> shape. Session-token validation is symmetric: both
/// LoginServer and Sentinel want the <i>same</i> 32-byte secret, so one
/// method serves both. Zone registration is asymmetric: ZoneManager needs
/// only the public half and zones need only the private half, and — the
/// load-bearing distinction — a zone process must <b>never</b> be able to
/// generate the pair. A zone that could mint its own keypair could forge a
/// trusted identity, defeating the gate entirely. The two entry points
/// therefore split by role and by generation authority:
/// <list type="bullet">
///   <item><description><see cref="LoadOrCreatePublic"/> — ZoneManager side.
///   Generates the pair on first boot if absent, persists both halves, and
///   returns the public key. This is the <i>only</i> path that generates.
///   </description></item>
///   <item><description><see cref="LoadSeed"/> — zone side. Load-only. A
///   missing seed is a fatal deploy error (the seed was never cloned from
///   ZoneManager), not a cue to generate — so it logs and throws rather
///   than silently minting an untrusted key.</description></item>
/// </list>
/// <para>
/// <b>Write-back flush caveat.</b> <see cref="DiskManager.WriteBinFile"/> is
/// write-back cached: the keypair files generated by
/// <see cref="LoadOrCreatePublic"/> are not physically on disk until the
/// next flush (timer-driven, size-triggered, or the shutdown flush). The
/// operational consequence is for the clone step: the seed file is not
/// safely copyable to a zone box until ZoneManager has flushed — the
/// reliable sequence is to let ZoneManager boot and shut down cleanly
/// (its <c>finally</c> runs the shutdown flush) <i>before</i> copying
/// <c>zone_registration_seed.key</c> out. Within a single running process,
/// reads see the cached bytes immediately, so first-boot generate-then-use
/// on the ZoneManager side is safe without a flush.
/// </para>
/// <para>
/// <b>Persist-failure caveat.</b> Because <see cref="DiskManager.WriteBinFile"/>
/// returns before the disk write is attempted, a flush that later fails
/// (e.g. full disk, permissions) is logged to <c>Console.Error</c> by
/// DiskManager but cannot be observed here. A failed keypair persist would
/// therefore surface only later, as a zone unable to authenticate. This is
/// a known DiskManager latent, not specific to this provider.
/// </para>
/// </remarks>
public static class ZoneRegistrationKeyProvider
{
    private const string SeedRelativePath =
        "keys/zone_registration_seed.key";
    private const string PublicRelativePath =
        "keys/zone_registration_public.key";

    private const int SeedLength = 32;
    private const int PublicKeyLength = 32;

    /// <summary>
    /// Loads the zone-registration public key for verification, generating
    /// and persisting a fresh keypair on first boot if none exists yet. This
    /// is the ZoneManager-side entry point and the only path that generates.
    /// </summary>
    /// <returns>The 32-byte Ed25519 public key ZoneManager verifies
    /// registration signatures against.</returns>
    /// <exception cref="InvalidOperationException">A persisted public key
    /// exists on disk but is not exactly <see cref="PublicKeyLength"/> bytes,
    /// indicating a corrupt or truncated key file that must not be trusted.
    /// </exception>
    /// <remarks>
    /// On a genuine first boot (neither file present) the pair is generated
    /// via <see cref="Ed25519KeyGenerator.Generate"/>, both halves are
    /// written, and the public half is returned. A missing file is caught
    /// and treated as first boot; a present-but-wrong-length file is <i>not</i>
    /// silently regenerated — regenerating would invalidate every zone's
    /// already-cloned seed, so a corrupt public key throws to force operator
    /// attention instead.
    /// </remarks>
    public static byte[] LoadOrCreatePublic()
    {
        DiskManager disk = DiskManager.Instance;

        try
        {
            byte[] existing = disk.ReadBinFile(PublicRelativePath);

            if (existing.Length == PublicKeyLength)
                return existing;

            // A wrong-length file is corruption, not absence. Regenerating
            // here would silently strand every zone's cloned seed, so this
            // is a loud stop rather than a quiet re-mint.
            throw new InvalidOperationException(
                $"Zone registration public key at '{PublicRelativePath}' "
                + $"is {existing.Length} bytes, expected "
                + $"{PublicKeyLength}. Refusing to regenerate over a "
                + "corrupt key (would invalidate cloned zone seeds).");
        }
        catch (FileNotFoundException)
        {
            // First boot: no key yet. Fall through to generate.
        }
        catch (DirectoryNotFoundException)
        {
            // First boot: keys directory absent. Fall through to generate.
        }

        Ed25519KeyPair pair = Ed25519KeyGenerator.Generate();

        // Seed first, then public — same safety ordering rationale as the
        // character write path: the seed is the half that must survive to be
        // cloned, so it is committed to the cache first.
        disk.WriteBinFile(SeedRelativePath, pair.PrivateSeed);
        disk.WriteBinFile(PublicRelativePath, pair.PublicKey);

        Scribe.Pump(new ScribeMessage(ScribeSeverity.Info,
            "Generated a new zone registration keypair. Clone "
            + $"'{SeedRelativePath}' to each zone host after the next "
            + "disk flush."));

        return pair.PublicKey;
    }

    /// <summary>
    /// Loads the zone-registration private seed a zone process signs with.
    /// Load-only: a missing or malformed seed is a fatal, unrecoverable
    /// deploy error and is never generated here.
    /// </summary>
    /// <returns>The 32-byte Ed25519 private seed the zone signs its
    /// registration timestamp with.</returns>
    /// <exception cref="FileNotFoundException">The seed file does not exist —
    /// it was never cloned from ZoneManager.</exception>
    /// <exception cref="DirectoryNotFoundException">The keys directory does
    /// not exist on this host.</exception>
    /// <exception cref="InvalidOperationException">The seed file exists but
    /// is not exactly <see cref="SeedLength"/> bytes.</exception>
    /// <remarks>
    /// Every failure is logged at <see cref="ScribeSeverity.Error"/> before
    /// it propagates, so the reason is on the record even though the caller
    /// (the zone process's entry point) is expected to treat the throw as a
    /// hard stop and shut down. The provider deliberately does not shut the
    /// process down itself — that lifecycle decision belongs to the process,
    /// which routes the throw into its existing clean-teardown path, the
    /// same way LoginServer refuses to start on a bad bind address.
    /// </remarks>
    public static byte[] LoadSeed()
    {
        DiskManager disk = DiskManager.Instance;

        byte[] seed;

        try
        {
            seed = disk.ReadBinFile(SeedRelativePath);
        }
        catch (Exception ex)
            when (ex is FileNotFoundException or DirectoryNotFoundException)
        {
            Scribe.Pump(new ScribeMessage(ScribeSeverity.Error,
                "Zone registration seed not found at "
                + $"'{SeedRelativePath}'. It must be cloned from the "
                + "ZoneManager host before a zone can register.", ex));
            throw;
        }

        if (seed.Length != SeedLength)
        {
            var ex = new InvalidOperationException(
                $"Zone registration seed at '{SeedRelativePath}' is "
                + $"{seed.Length} bytes, expected {SeedLength}. The seed "
                + "file is corrupt or truncated.");

            Scribe.Pump(new ScribeMessage(ScribeSeverity.Error,
                "Zone registration seed is malformed.", ex));
            throw ex;
        }

        return seed;
    }
}

/*
 *------------------------------------------------------------
 * (ZoneRegistrationKeyProvider.cs)
 * See License.txt for licensing information.
 *-----------------------------------------------------------
 */